apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer-service
        image: analyzer-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer
spec:
  selector:
    app: analyzer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
